# Generated by Django 5.1.7 on 2025-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='water_intake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
