# Generated by Django 5.1.7 on 2025-04-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dailylog_water_intake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailylog',
            old_name='excersise_done',
            new_name='exercise_done',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='exercise_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
