# Generated by Django 5.1.7 on 2025-04-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_excersise_done_dailylog_exercise_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailylog',
            old_name='exercise_done',
            new_name='excersise_done',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='exercise_duration',
        ),
    ]
